export const PautarSessaoElements = {
  abaPauta: '#cdk-step-label-0-2',
  selecionarProcesso: '#mat-mdc-checkbox-1-input',
  btnAdicionarNaPauta: '[data-test="botao-adicionar-pauta"]',
  salvarCadastro: '[data-test="botao-salvar-cadastro"]',
  checkProcessos: '.mdc-checkbox__native-control',
  removerProcessos: '.content-remover-pauta.ng-star-inserted',
  adicionarProcessoPauta: '.content-adicionar-pauta.ng-star-inserted',
  btnAdicionarRemoverProcessosPauta: '.mdc-button__label',
  btnAjudaPasso1: '[data-test="botao-ajuda-selecionar-processo"]',
  btnAjudaPasso2: '[data-test="botao-ajuda-definir-pauta"]',
  btnFiltrosPasso1: '[data-test="botao-todos-filtros"]',
  btnFiltrosPasso2: '[data-test="botao-todos-filtros"]',
  paginador: '.mat-mdc-paginator',
  listaProcessos: '.list',
  cardProcessos: '.card-content',
  btnSelecionarTodosProcessos: '[data-test="selecionar-todos"]',
  descricaoFiltroOrgaoJulgador: '[datatest="input-autocomplete-orgao-julgador"]',
  descricaoFiltroSituacao: ['datatest="input-autocomplete-situacao"'],
  acoes: '.mat-mdc-button-touch-target',
  copiarNumeroProcesso: '[datatest="copiar-numero-processo"]',
  numeroProcessoCardLista: '.numero-processo',
  descricoesCards: '.item',

  // filtros
  numeroProcessoInteiro: '[datatest="filtro-input-text-numero-processo"]',
  numeroProcessoBloco1: '[data-test="processo-bloco-1"]',
  numeroProcessoBloco2: '[data-test="processo-bloco-2"]',
  numeroProcessoBloco3: '[data-test="processo-bloco-3"]',
  numeroProcessoBloco4: '[data-test="processo-bloco-4"]',
  numeroProcessoBloco5: '[data-test="processo-bloco-5"]',
  numeroProcessoBloco6: '[data-test="processo-bloco-6"]',
  situacaoProcesso: '[datatest="filtro-input-autocomplete-resultado-sessao-anterior"]',
  orgaoJulgador: '[data-test="input-autocomplete-orgao-julgador"]',
  classeJudicial: '[data-test="input-autocomplete-classe-judicial"]',
  assunto: '[data-test="input-autocomplete-assunto"]',
  dataInicioFim: '[data-test="input-datepicker-data-inicio"]',
  etiquetas: '[data-test="input-autocomplete-chips-etiqueta"]',
  btnLimpar: '[data-test="filtro-botao-limpar"]',
  btnFiltrar: '[data-test="filtro-botao-filtrar"]',
  btnContinuar: '[data-test="botao-continuar-pautar-sessao"]',
  btnFecharModal1: '[data-test="botao-fechar-dialogo"]',
  btnFecharModal2: '[data-test="botao-fechar-dialogo"]',

  // reordenação pauta
  descricaoReordenarPauta: '.descricao',
  btnCancelarReordenacaoPauta: '.mat-mdc-card > .acoes > .mat-mdc-tooltip-trigger > .mat-icon',
  btnConfirmarReordenacaoPauta: '.mdc-button__label',
  btnReordenarPauta: '[data-test="botao-reordenar-pauta"]',
  btnDragAndDrop: '[data-test="card-processo-1506"]',
  tituloDialogReordenarProcesso: '#mat-mdc-dialog-title-0',
  posicaoDe: '[data-test="input-text-de"]',
  posicaoPara: '[data-test="input-text-para"]',
  tituloReordenarPauta: '.titulo',
  btnReordenarModalDePara: '[data-test="botao-reordenar-processo"]',

  // Ver composição
  btnMaisOpcoes: '[mattooltip="Mais opções"]',
  btnOpcoes: '[data-test="menu-1768"]',
  btnListaOpcoes: '.menu-item',
  btnRemoverOrgaoJulgador: '[data-test="botao-remover-orgao-julgador"]',
  btnFecharModalVerComposicao: '[data-test="botao-fechar-dialogo"]',
  btnAlterarRepresentante: '[data-test="botao-alterar-composicao"]',
  contadorComposicaoIndividual: '.processos-pautados-quantidade ng-star-inserted',
  tituloModal: '.dialog-header',
  listaOrgaoJulgador: 'mat-option .mdc-list-item__primary-text',
  listaRepresentante: 'mat-option .mdc-list-item__primary-text',
  fecharModalComposicaoIndividual: '[data-test="botao-fechar-dialogo"]'

}
